// ===================== DEVELOPER SITEPLAN — 3D VIEWER =====================
// Self-contained Three.js scene showing the housing complex generated by Developer Mode.
let dv3 = { renderer:null, scene:null, camera:null, raf:null,
  orbit:{ on:false, pan:false, lx:0, ly:0, theta:38, phi:55, radius:90, tx:0, tz:0 } };

function openDev3D() {
  if (!devLastPlan) { showNotif('⚠️ Generate siteplan dulu'); return; }
  document.getElementById('modalDev3D').classList.add('show');
  setTimeout(initDev3D, 100);
}
function closeDev3D() {
  document.getElementById('modalDev3D').classList.remove('show');
  disposeDev3D();
}
function disposeDev3D() {
  if (dv3.raf) { cancelAnimationFrame(dv3.raf); dv3.raf = null; }
  if (dv3.renderer) { dv3.renderer.dispose(); const c = document.getElementById('dev3d-canvas-container'); if (c) c.innerHTML=''; dv3.renderer = null; }
  dv3.scene = null; dv3.camera = null;
}

function initDev3D() {
  disposeDev3D();
  const loading = document.getElementById('dev3d-loading'); loading.style.display = 'flex';
  const cont = document.getElementById('dev3d-canvas-container');
  const W = cont.clientWidth, H = cont.clientHeight;

  const scene = new THREE.Scene();
  scene.background = makeSkyTexture();
  scene.fog = new THREE.Fog(0xbcd4ea, 160, 360);
  dv3.scene = scene;

  const cam = new THREE.PerspectiveCamera(46, W/H, 0.5, 1000);
  dv3.camera = cam;

  const rend = new THREE.WebGLRenderer({ antialias:true, preserveDrawingBuffer:true });
  rend.setSize(W, H); rend.setPixelRatio(Math.min(devicePixelRatio, 2));
  rend.shadowMap.enabled = true; rend.shadowMap.type = THREE.PCFSoftShadowMap;
  if (THREE.sRGBEncoding) rend.outputEncoding = THREE.sRGBEncoding;
  if (THREE.ACESFilmicToneMapping) { rend.toneMapping = THREE.ACESFilmicToneMapping; rend.toneMappingExposure = 1.04; }
  cont.appendChild(rend.domElement); dv3.renderer = rend;

  // lights
  scene.add(new THREE.AmbientLight(0xdfe9ff, 0.42));
  scene.add(new THREE.HemisphereLight(0xcfe2ff, 0x5a6b4a, 0.7));
  const sunAz = (northAngle + 135) * Math.PI/180;
  const sun = new THREE.DirectionalLight(0xfff1d6, 2.1);
  sun.position.set(Math.sin(sunAz)*90, 130, Math.cos(sunAz)*90);
  sun.castShadow = true; sun.shadow.mapSize.set(2048,2048);
  const sc = sun.shadow.camera; sc.near=1; sc.far=420; sc.left=-130; sc.right=130; sc.top=130; sc.bottom=-130;
  sun.shadow.bias = -0.0004; sun.shadow.normalBias = 0.02;
  scene.add(sun);

  buildDev3DComplex(scene, devLastPlan, devState);

  rend.domElement.addEventListener('mousedown', dev3DDown);
  rend.domElement.addEventListener('contextmenu', e=>e.preventDefault());
  window.addEventListener('mousemove', dev3DMove);
  window.addEventListener('mouseup', dev3DUp);
  rend.domElement.addEventListener('wheel', dev3DWheel, { passive:false });
  // TOUCH (HP/tablet): 1 jari orbit, 2 jari cubit zoom + geser
  rend.domElement.addEventListener('touchstart', dev3DTouchStart, { passive:false });
  rend.domElement.addEventListener('touchmove', dev3DTouchMove, { passive:false });
  rend.domElement.addEventListener('touchend', dev3DTouchEnd, { passive:false });
  rend.domElement.addEventListener('touchcancel', dev3DTouchEnd, { passive:false });
  window.addEventListener('resize', dev3DResize);

  resetDev3DCamera();
  loading.style.display = 'none';
  (function loop(){ dv3.raf = requestAnimationFrame(loop); rend.render(scene, cam); })();
}

function buildDev3DComplex(scene, p, d) {
  const W = d.landW, L = d.landH;
  const cx = W/2, cz = L/2;

  // ground (grass) — textured
  const grassTex = texGrass(); grassTex.repeat.set(W*0.6, L*0.6);
  const grass = new THREE.Mesh(new THREE.PlaneGeometry(W*2.6, L*2.6),
    new THREE.MeshStandardMaterial({ map:grassTex, roughness:1 }));
  grass.rotation.x = -Math.PI/2; grass.position.set(0,-0.02,0); grass.receiveShadow = true; scene.add(grass);

  // land base (mowed lawn, lighter)
  const landTex = texGrass(0.12); landTex.repeat.set(W*0.5, L*0.5);
  const land = new THREE.Mesh(new THREE.PlaneGeometry(W, L),
    new THREE.MeshStandardMaterial({ map:landTex, roughness:1 }));
  land.rotation.x = -Math.PI/2; land.position.set(0,0.001,0); land.receiveShadow = true; scene.add(land);

  const houseCols = ['#eae4d6','#dcd3c0','#e6ddcb','#d3c9b4','#efe8d8','#cdd6da','#e8d9c4'];
  const roofTex = texRoofTiles();
  const wallRough = 0.92;
  const blockH = d.roadW + p.u.kavD*2;

  let n = 0;
  for (let bl=0; bl<p.blocks; bl++) {
    const blockTopZ = bl*blockH;
    // ROAD strip (asphalt texture)
    const aTex = texAsphalt(); aTex.repeat.set(W*0.18, d.roadW*0.18);
    const road = new THREE.Mesh(new THREE.BoxGeometry(W, 0.08, d.roadW),
      new THREE.MeshStandardMaterial({ map:aTex, roughness:0.95 }));
    road.position.set(0, 0.04, (blockTopZ + d.roadW/2) - cz); road.receiveShadow = true; scene.add(road);
    // center dashes
    const dashN = Math.floor(W/2);
    for (let i=0;i<dashN;i++){
      const dash = new THREE.Mesh(new THREE.BoxGeometry(1.0,0.09,0.18), new THREE.MeshStandardMaterial({color:0xe8d98a, roughness:0.7, emissive:0x33301a}));
      dash.position.set(-W/2 + 1 + i*2, 0.085, (blockTopZ + d.roadW/2) - cz); scene.add(dash);
    }

    [0,1].forEach(rowi=>{
      const rowZ0 = blockTopZ + d.roadW + rowi*p.u.kavD;
      for (let col=0; col<p.cols; col++) {
        const kx0 = col*p.u.kavW;
        const plotCx = (kx0 + p.u.kavW/2) - cx;
        const plotCz = (rowZ0 + p.u.kavD/2) - cz;
        const frontIsTop = rowi===0;             // front faces the road
        const twoStorey = devState.type>=60;

        // yard slab (concrete-ish in front, grass behind handled by land)
        // house
        const hw = Math.min(p.u.kavW-1.2, p.u.kavW*0.78);
        const hd = p.u.kavD*0.5;
        const hh = twoStorey ? 6.0 : 3.3;
        const frontGap = 1.2;
        const hz = frontIsTop
          ? (rowZ0 + frontGap + hd/2) - cz
          : (rowZ0 + p.u.kavD - frontGap - hd/2) - cz;

        const wallMat = new THREE.MeshStandardMaterial({ color:new THREE.Color(houseCols[n%houseCols.length]), roughness:wallRough });
        const body = new THREE.Mesh(new THREE.BoxGeometry(hw, hh, hd), wallMat);
        body.position.set(plotCx, hh/2+0.05, hz); body.castShadow = true; body.receiveShadow = true; scene.add(body);

        // façade details on the side facing the road
        const faceZ = frontIsTop ? hz - hd/2 - 0.04 : hz + hd/2 + 0.04;
        const faceDir = frontIsTop ? -1 : 1;
        addFacade(scene, plotCx, hz, hw, hd, hh, faceZ, faceDir, twoStorey, n);

        // gable roof (textured tiles)
        const roofH = 1.5 + (twoStorey?0.5:0);
        const roof = makeGable(hw+0.7, hd+0.7, roofH, roofTex, n);
        roof.position.set(plotCx, hh+0.05, hz); scene.add(roof);

        // carport canopy + car (alternating)
        if (p.u.kavW >= 5.5) {
          const cpW = 2.4, cpD = hd*0.7;
          const cpZ = frontIsTop ? hz - hd/2 - cpD/2 - 0.2 : hz + hd/2 + cpD/2 + 0.2;
          const canopy = new THREE.Mesh(new THREE.BoxGeometry(cpW, 0.12, cpD), new THREE.MeshStandardMaterial({color:0xcfd3da, roughness:0.6, metalness:0.3}));
          canopy.position.set(plotCx + hw*0.28, 2.3, cpZ); canopy.castShadow=true; scene.add(canopy);
          if (n % 2 === 0) scene.add(makeCar(plotCx + hw*0.28, cpZ, frontIsTop, n));
        }

        // small tree in the back yard
        if (n % 3 === 0) {
          const ty = frontIsTop ? plotCz + p.u.kavD*0.32 : plotCz - p.u.kavD*0.32;
          scene.add(makeTree(plotCx + (n%2?1:-1)*hw*0.3, ty, 0.8 + (n%3)*0.2));
        }
        n++;
      }
    });
  }

  // perimeter fence (low wall + posts)
  const fenceMat = new THREE.MeshStandardMaterial({ color:0xc4c8d0, roughness:0.85 });
  const mkWall=(w,h,dp,x,y,z)=>{ const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,dp),fenceMat); m.position.set(x,y,z); m.castShadow=true; m.receiveShadow=true; scene.add(m); };
  mkWall(W+0.4,0.8,0.25, 0,0.4,-cz);  mkWall(W+0.4,0.8,0.25, 0,0.4, cz);
  mkWall(0.25,0.8,L, -cx,0.4,0);  mkWall(0.25,0.8,L,  cx,0.4,0);
  // gate posts at front
  [-cx, cx].forEach(px=>{ const post=new THREE.Mesh(new THREE.BoxGeometry(0.5,1.6,0.5), new THREE.MeshStandardMaterial({color:0x9aa0aa, roughness:0.8})); post.position.set(px,0.8,-cz); post.castShadow=true; scene.add(post); });

  // boundary trees along sides
  const nTrees = Math.max(3, Math.floor(L/8));
  for (let i=0;i<nTrees;i++){
    const tz = -cz + 3 + i*(L-6)/(nTrees-1||1);
    scene.add(makeTree(-cx-1.4, tz, 1.1));
    scene.add(makeTree( cx+1.4, tz, 1.1));
  }

  // north arrow marker
  const nCanvas = document.createElement('canvas'); nCanvas.width=nCanvas.height=128;
  const g=nCanvas.getContext('2d'); g.translate(64,64); g.rotate(-northAngle*Math.PI/180);
  g.fillStyle='#e8523a'; g.beginPath(); g.moveTo(0,-40); g.lineTo(14,10); g.lineTo(0,2); g.lineTo(-14,10); g.closePath(); g.fill();
  g.rotate(northAngle*Math.PI/180); g.fillStyle='#fff'; g.font='bold 30px sans-serif'; g.textAlign='center'; g.fillText('U',0,-46);
  const spr = new THREE.Sprite(new THREE.SpriteMaterial({ map:new THREE.CanvasTexture(nCanvas), transparent:true, depthTest:false }));
  spr.position.set(-cx-4, 7, -cz-4); spr.scale.set(7,7,1); scene.add(spr);
}

// add windows + door on the façade plane
function addFacade(scene, cxp, hz, hw, hd, hh, faceZ, dir, twoStorey, n) {
  const glassMat = new THREE.MeshStandardMaterial({ color:0x9fc4d6, roughness:0.12, metalness:0.5, emissive:0x16323f, emissiveIntensity:0.35 });
  const frameMat = new THREE.MeshStandardMaterial({ color:0x3a3f47, roughness:0.7 });
  const doorMat  = new THREE.MeshStandardMaterial({ color:0x5b4632, roughness:0.65 });
  const t = 0.06;
  const win = (wx, wy, ww, wh) => {
    const fr = new THREE.Mesh(new THREE.BoxGeometry(ww+0.14, wh+0.14, t), frameMat);
    fr.position.set(cxp+wx, wy, faceZ + dir*0.01); fr.castShadow=true; scene.add(fr);
    const gl = new THREE.Mesh(new THREE.BoxGeometry(ww, wh, t*0.6), glassMat);
    gl.position.set(cxp+wx, wy, faceZ + dir*0.05); scene.add(gl);
  };
  // ground floor: door + window
  const door = new THREE.Mesh(new THREE.BoxGeometry(0.95, 2.05, t*1.5), doorMat);
  door.position.set(cxp - hw*0.26, 1.05, faceZ + dir*0.02); door.castShadow=true; scene.add(door);
  win(hw*0.20, 1.35, 1.3, 1.1);
  // upper floor windows
  if (twoStorey) { win(-hw*0.24, 4.2, 1.0, 1.0); win(hw*0.22, 4.2, 1.3, 1.0); }
}

function makeCar(x, z, frontIsTop, n) {
  const grp = new THREE.Group();
  const cols = [0x2c3e8f,0x8f2c2c,0x2c5a2c,0x444444,0xddddee];
  const body = new THREE.Mesh(new THREE.BoxGeometry(1.7,0.55,3.9), new THREE.MeshStandardMaterial({color:cols[n%cols.length], roughness:0.35, metalness:0.5}));
  body.position.y=0.55; body.castShadow=true; grp.add(body);
  const cabin = new THREE.Mesh(new THREE.BoxGeometry(1.5,0.5,2.0), new THREE.MeshStandardMaterial({color:0x223044, roughness:0.2, metalness:0.4}));
  cabin.position.set(0,1.0,-0.2); grp.add(cabin);
  [[-0.85,1.2],[0.85,1.2],[-0.85,-1.2],[0.85,-1.2]].forEach(([wx,wz])=>{
    const wheel=new THREE.Mesh(new THREE.CylinderGeometry(0.34,0.34,0.25,14), new THREE.MeshStandardMaterial({color:0x111114, roughness:0.8}));
    wheel.rotation.z=Math.PI/2; wheel.position.set(wx,0.34,wz); grp.add(wheel);
  });
  grp.position.set(x, 0, z); grp.rotation.y = 0; return grp;
}

function makeTree(x, z, s=1) {
  const grp = new THREE.Group();
  const trunk = new THREE.Mesh(new THREE.CylinderGeometry(0.12*s,0.16*s,1.2*s,8), new THREE.MeshStandardMaterial({color:0x6b4a2b, roughness:0.9}));
  trunk.position.y=0.6*s; trunk.castShadow=true; grp.add(trunk);
  const greens=[0x3f7a36,0x4a8c3e,0x356b30];
  for (let i=0;i<3;i++){
    const foli=new THREE.Mesh(new THREE.IcosahedronGeometry((0.9-i*0.18)*s,0), new THREE.MeshStandardMaterial({color:greens[i%3], roughness:1, flatShading:true}));
    foli.position.y=(1.3+i*0.5)*s; foli.castShadow=true; grp.add(foli);
  }
  grp.position.set(x,0,z); return grp;
}

function makeGable(w, dp, h, roofTex, n) {
  const grp = new THREE.Group();
  const pos = [], uv = [];
  const tri=(a,b,c, ua,ub,uc)=>{ pos.push(...a,...b,...c); uv.push(...ua,...ub,...uc); };
  const x=w/2, z=dp/2;
  // two slopes (with UVs for tile texture)
  tri([-x,0,-z],[ x,0,-z],[ x,h,0], [0,0],[1,0],[1,1]); tri([-x,0,-z],[ x,h,0],[-x,h,0], [0,0],[1,1],[0,1]);
  tri([-x,0, z],[ x,0, z],[ x,h,0], [0,0],[1,0],[1,1]); tri([-x,0, z],[ x,h,0],[-x,h,0], [0,0],[1,1],[0,1]);
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(new Float32Array(pos),3));
  geo.setAttribute('uv', new THREE.BufferAttribute(new Float32Array(uv),2));
  geo.computeVertexNormals();
  const tex = roofTex.clone(); tex.needsUpdate = true; tex.repeat.set(2.2, 1.4);
  const mesh = new THREE.Mesh(geo, new THREE.MeshStandardMaterial({ map:tex, roughness:0.85, side:THREE.DoubleSide }));
  mesh.castShadow = true; mesh.receiveShadow = true; grp.add(mesh);
  // gable end walls (triangles) — match wall tone
  const endMat = new THREE.MeshStandardMaterial({ color:0xded5c2, roughness:0.92, side:THREE.DoubleSide });
  [-1,1].forEach(sgn=>{
    const ep=[]; const ex=sgn*x;
    ep.push(ex,0,-z, ex,0,z, ex,h,0);
    const eg=new THREE.BufferGeometry(); eg.setAttribute('position', new THREE.BufferAttribute(new Float32Array(ep),3)); eg.computeVertexNormals();
    const em=new THREE.Mesh(eg, endMat); em.castShadow=true; grp.add(em);
  });
  return grp;
}

// ---------- procedural textures (cached) ----------
let _texCache = {};
function texGrass(light=0) {
  const c=document.createElement('canvas'); c.width=c.height=128; const g=c.getContext('2d');
  g.fillStyle=`rgb(${90+light*60},${130+light*50},${70+light*40})`; g.fillRect(0,0,128,128);
  for(let i=0;i<2600;i++){ const v=Math.random(); g.fillStyle=`rgba(${40+v*70},${90+v*90},${40+v*50},0.5)`; g.fillRect(Math.random()*128,Math.random()*128,1.5,1.5); }
  const t=new THREE.CanvasTexture(c); t.wrapS=t.wrapT=THREE.RepeatWrapping; if(THREE.sRGBEncoding)t.encoding=THREE.sRGBEncoding; return t;
}
function texAsphalt() {
  const c=document.createElement('canvas'); c.width=c.height=128; const g=c.getContext('2d');
  g.fillStyle='#34373d'; g.fillRect(0,0,128,128);
  for(let i=0;i<3000;i++){ const v=Math.random(); g.fillStyle=`rgba(${v*120|0},${v*120|0},${v*130|0},0.35)`; g.fillRect(Math.random()*128,Math.random()*128,1.4,1.4); }
  const t=new THREE.CanvasTexture(c); t.wrapS=t.wrapT=THREE.RepeatWrapping; if(THREE.sRGBEncoding)t.encoding=THREE.sRGBEncoding; return t;
}
function texRoofTiles() {
  if (_texCache.roof) return _texCache.roof;
  const c=document.createElement('canvas'); c.width=c.height=128; const g=c.getContext('2d');
  g.fillStyle='#9c4128'; g.fillRect(0,0,128,128);
  for(let y=0;y<128;y+=16){ for(let x=0;x<128;x+=22){ const off=(y/16)%2?11:0; g.fillStyle=`hsl(${10+Math.random()*8},${55+Math.random()*15}%,${36+Math.random()*10}%)`; g.beginPath(); g.moveTo(x+off,y); g.arc(x+off+11,y+8,11,Math.PI,0,true); g.lineTo(x+off+22,y+16); g.lineTo(x+off,y+16); g.closePath(); g.fill(); g.strokeStyle='rgba(0,0,0,0.18)'; g.stroke(); } }
  const t=new THREE.CanvasTexture(c); t.wrapS=t.wrapT=THREE.RepeatWrapping; if(THREE.sRGBEncoding)t.encoding=THREE.sRGBEncoding; _texCache.roof=t; return t;
}
function makeSkyTexture() {
  const c=document.createElement('canvas'); c.width=16; c.height=256; const g=c.getContext('2d');
  const grd=g.createLinearGradient(0,0,0,256); grd.addColorStop(0,'#5b95d6'); grd.addColorStop(0.5,'#9cc4e6'); grd.addColorStop(1,'#d8e8f2');
  g.fillStyle=grd; g.fillRect(0,0,16,256);
  const t=new THREE.CanvasTexture(c); if(THREE.sRGBEncoding)t.encoding=THREE.sRGBEncoding; return t;
}

// ---- camera / controls ----
function updateDev3DCam() {
  const o = dv3.orbit; if (!dv3.camera) return;
  const t=o.theta*Math.PI/180, p=o.phi*Math.PI/180, r=o.radius;
  dv3.camera.position.set(o.tx + r*Math.sin(p)*Math.sin(t), r*Math.cos(p), o.tz + r*Math.sin(p)*Math.cos(t));
  dv3.camera.lookAt(o.tx, 0, o.tz);
}
function resetDev3DCamera() {
  const o = dv3.orbit;
  o.theta=38; o.phi=56; o.radius = Math.max(devState.landW, devState.landH) * 1.25 + 30;
  o.tx=0; o.tz=0; updateDev3DCam();
}
function dev3DDown(e){ if(e.button===0) dv3.orbit.on=true; if(e.button===2) dv3.orbit.pan=true; dv3.orbit.lx=e.clientX; dv3.orbit.ly=e.clientY; }
function dev3DUp(){ dv3.orbit.on=false; dv3.orbit.pan=false; }
function dev3DMove(e){
  if (!dv3.renderer) return;
  const o=dv3.orbit, dx=e.clientX-o.lx, dy=e.clientY-o.ly; o.lx=e.clientX; o.ly=e.clientY;
  if (o.on){ o.theta-=dx*0.4; o.phi=Math.max(8,Math.min(85,o.phi+dy*0.4)); updateDev3DCam(); }
  if (o.pan){ const sp=o.radius*0.0022, t=o.theta*Math.PI/180; o.tx-=(Math.cos(t)*dx-Math.sin(t)*dy)*sp; o.tz+=(Math.sin(t)*dx+Math.cos(t)*dy)*sp; updateDev3DCam(); }
}
function dev3DWheel(e){ e.preventDefault(); dv3.orbit.radius=Math.max(12,Math.min(400,dv3.orbit.radius+e.deltaY*0.06)); updateDev3DCam(); }

// ---- touch controls (HP/tablet) ----
let dvTouch = { mode:null, lx:0, ly:0, lastDist:0, lmx:0, lmy:0 };
function _dvDist(t){ return Math.hypot(t[0].clientX-t[1].clientX, t[0].clientY-t[1].clientY); }
function dev3DTouchStart(e){
  if(!dv3.renderer) return; e.preventDefault();
  const t=e.touches;
  if(t.length===1){ dvTouch.mode='one'; dvTouch.lx=t[0].clientX; dvTouch.ly=t[0].clientY; }
  else if(t.length>=2){ dvTouch.mode='two'; dvTouch.lastDist=_dvDist(t); dvTouch.lmx=(t[0].clientX+t[1].clientX)/2; dvTouch.lmy=(t[0].clientY+t[1].clientY)/2; }
}
function dev3DTouchMove(e){
  if(!dv3.renderer) return; e.preventDefault();
  const t=e.touches, o=dv3.orbit;
  if(dvTouch.mode==='one' && t.length===1){
    const dx=t[0].clientX-dvTouch.lx, dy=t[0].clientY-dvTouch.ly; dvTouch.lx=t[0].clientX; dvTouch.ly=t[0].clientY;
    o.theta-=dx*0.4; o.phi=Math.max(8,Math.min(85,o.phi+dy*0.4)); updateDev3DCam();
  } else if(dvTouch.mode==='two' && t.length>=2){
    const dist=_dvDist(t);
    if(dvTouch.lastDist>0){ o.radius=Math.max(12,Math.min(400, o.radius*(dvTouch.lastDist/dist))); }
    dvTouch.lastDist=dist;
    const mx=(t[0].clientX+t[1].clientX)/2, my=(t[0].clientY+t[1].clientY)/2;
    const pdx=mx-dvTouch.lmx, pdy=my-dvTouch.lmy; dvTouch.lmx=mx; dvTouch.lmy=my;
    const sp=o.radius*0.0022, th=o.theta*Math.PI/180;
    o.tx-=(Math.cos(th)*pdx-Math.sin(th)*pdy)*sp; o.tz+=(Math.sin(th)*pdx+Math.cos(th)*pdy)*sp;
    updateDev3DCam();
  }
}
function dev3DTouchEnd(e){
  const t=e.touches;
  if(t.length===0) dvTouch.mode=null;
  else if(t.length===1){ dvTouch.mode='one'; dvTouch.lx=t[0].clientX; dvTouch.ly=t[0].clientY; }
}
function dev3DResize(){
  if (!dv3.renderer) return;
  const cont=document.getElementById('dev3d-canvas-container'); if(!cont) return;
  dv3.camera.aspect=cont.clientWidth/cont.clientHeight; dv3.camera.updateProjectionMatrix();
  dv3.renderer.setSize(cont.clientWidth, cont.clientHeight);
}
